### ISSUE TITLE
home > hero bg photo should not stretch

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#1]
right now on certain window size range, the photo stretch like this screenshot below.
![image](https://cloud.githubusercontent.com/assets/3534617/15696126/82861674-2762-11e6-95e7-ece5df3f6650.png)

**Comment by skinall13** [comment]
We have solved the hero background image issue, now its working fine on ever window size. 
Please find the screenshot below
![hero banner](https://cloud.githubusercontent.com/assets/19643270/15823191/40dc5508-2c17-11e6-917e-adfde4ff57d6.png)

**Comment by kurumi0909** [comment]
i think it's still stretching on this view?
![image](https://cloud.githubusercontent.com/assets/3534617/15848934/97689c1a-2c44-11e6-86ee-ac71cb06e7a7.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/

**Comment by kurumi0909** [comment]
I'm not sure what happened but the image is too big now. Am i seeing the latest build?
![image](https://cloud.githubusercontent.com/assets/3534617/15916455/1cd38ac2-2da8-11e6-8f9a-6e41cfa9d05f.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below

http://dev.sitessimply.com/html/kacostar/
