### ISSUE TITLE
product detail > write a review: content should be empty and expand content box for longer input

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#14]
all content should be visible when the user types more than one line
![image](https://cloud.githubusercontent.com/assets/3534617/15802075/9edd78d8-2a5c-11e6-8571-60e4673ac944.png)

**Comment by skinall13** [comment]
Issue Solved.
Please find the link below;

http://dev.sitessimply.com/html/kacostar/product-detail.html
