### ISSUE TITLE
global > header and footer: text should align and vertically centered

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#15]
on different viewpoints, they are all slightly off.
![image](https://cloud.githubusercontent.com/assets/3534617/15802195/7f93b084-2a5f-11e6-9352-17252b44db8d.png)
![image](https://cloud.githubusercontent.com/assets/3534617/15802201/a94cde14-2a5f-11e6-8bd0-5eec01ba66fe.png)
![image](https://cloud.githubusercontent.com/assets/3534617/15802211/fa723b04-2a5f-11e6-8bea-49497fdc9e1c.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/
