### ISSUE TITLE
global > nav font keep size 18px

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#16]
remove the mid-size window state
change 16px to 18px

@media only screen and (max-width: 992px)
.menu-top-small ul li a, .main-menu-top li a {
font-size: 18px;
}

![image](https://cloud.githubusercontent.com/assets/3534617/15802234/a35f4cca-2a60-11e6-8ff1-eaa269bd7157.png)

**Comment by skinall13** [comment]
On 992px screen size menu text  gets over laped at 18 px font size.
Need to made little changes on design if you want
We have attached the screenshot below;

![menu](https://cloud.githubusercontent.com/assets/19643270/15824916/2b605e74-2c1f-11e6-8844-8053462ed156.jpg)
