### ISSUE TITLE
product > hero description keep container shorter on (min-width: 768px)

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#17]
keep the width short like (min-width: 992px)
so that the text doesn't cover the image on the right

![image](https://cloud.githubusercontent.com/assets/3534617/15802267/6525e4ea-2a61-11e6-8d83-20d00fe71fef.png)

**Comment by skinall13** [comment]
Issue Solved.
Please find the link below;

http://dev.sitessimply.com/html/kacostar/product-detail.html
