### ISSUE TITLE
home > features bg photo should cover the full height of the div.

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#2]
on certain window views the bg photo floats. it should be scaled up to fit the full height of the section.
current site looks like this
![image](https://cloud.githubusercontent.com/assets/3534617/15696157/ca140ad2-2762-11e6-9d6b-ae15c10e510b.png)

**Comment by skinall13** [comment]
Floating issue  solved, now the image is stable on each and every screen resolution.

**Comment by kurumi0909** [comment]
i see that the images are attached to the bottom. is there a way to make the height of the photo to cover the height of the section? and i wouldn't want this to stretch
![image](https://cloud.githubusercontent.com/assets/3534617/15848904/6aedd0ec-2c44-11e6-9886-1cdd339657dc.png)

**Comment by skinall13** [comment]
image can not be stable on each and every screen resolution.  if image is  stable on each and every screen resolution image get stretch. 

Please find the screenshot below

![home](https://cloud.githubusercontent.com/assets/19643270/15890408/ffdf6b36-2d8c-11e6-8def-7148439c7312.png)

**Comment by kurumi0909** [comment]
i'm suggesting this
![image](https://cloud.githubusercontent.com/assets/3534617/15916418/b3c0f1f0-2da7-11e6-8545-9b89ac550eaf.png)

instead of this
![image](https://cloud.githubusercontent.com/assets/3534617/15916408/984fc57c-2da7-11e6-924b-6dee720ab30d.png)

so let's have the right part a bit cut off if it has to be that case.

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/

**Comment by kurumi0909** [comment]
i think it's stretching the photo a bit.
and there seems to be some paddings on left and right of the photo? can we remove that?
![image](https://cloud.githubusercontent.com/assets/3534617/15938753/709d225e-2e29-11e6-8c3c-ef7ab6c9f54a.png)

and also for mid-window size can we push the photos left and right so that they don't cover the text?
![image](https://cloud.githubusercontent.com/assets/3534617/15938779/8675fa2e-2e29-11e6-9401-271ffb3ae4cd.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/

**Comment by kurumi0909** [comment]
thank you!
