### ISSUE TITLE
my bag > 'continue shopping' button should be consistent with others

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#20]
there are 2 button sizes throughout the site

font size: 16px, button height: 40px
<img width="236" alt="screen shot 2016-06-04 at 2 42 41 pm" src="https://cloud.githubusercontent.com/assets/3534617/15802325/abbc8e58-2a62-11e6-9772-c56075b7b0f6.png">

font size: 24px, button height: 55px
<img width="211" alt="screen shot 2016-06-04 at 2 42 45 pm" src="https://cloud.githubusercontent.com/assets/3534617/15802326/ad3c37ec-2a62-11e6-8d86-7d9f0394cd5c.png">

please review all buttons so that they are consistent on all screen size view.
only 'check out' on my bag 'place your order' on checkout, and 'search' on store locator page have big buttons and all other buttons are the small ones.

**Comment by skinall13** [comment]
Issue Solved.
Please find the link below;

http://dev.sitessimply.com/html/kacostar/cart.html
