### ISSUE TITLE
Product > share expand on hover. and make them all caps

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#24]
can the share options expand on hover?
and the text needs to be all caps
the reference design is below
![image](https://cloud.githubusercontent.com/assets/3534617/15916499/707f648e-2da8-11e6-998e-3ab5aa2e9447.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/product-detail.html
