### ISSUE TITLE
global > nav hover / active state missing

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#3]
on hover and to indicate the current page, there should be underlines for text

see the reference below (approved design comp)
![image](https://cloud.githubusercontent.com/assets/3534617/15696270/c27b19a4-2763-11e6-80f9-0c586564cc16.png)

**Comment by skinall13** [comment]
We have placed underline  hover effect on active page.
Please find the link below:

http://dev.sitessimply.com/html/kacostar/product.html

**Comment by kurumi0909** [comment]
sorry can you also apply the same effect on sign in and my bag? thank you!!
![image](https://cloud.githubusercontent.com/assets/3534617/15848695/54202320-2c43-11e6-9266-a3676edc05a4.png)

**Comment by skinall13** [comment]
Done. 
Please find the link below;

http://dev.sitessimply.com/html/kacostar/
