### ISSUE TITLE
global > logo size should be 176 x 32 px and should also have retina asset

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#4]
please use 176x32 logo for normal and 352x64 for retina.
if you want me to create any assets, please assign it back to me
below is the design comp for reference
<img width="258" alt="screen shot 2016-06-04 at 1 34 54 pm" src="https://cloud.githubusercontent.com/assets/3534617/15801938/27722580-2a59-11e6-899b-bcd396f7054c.png">

**Comment by skinall13** [comment]
As per your requirement we have used 176x32 logo for normal and 352x64 for retina.
