### ISSUE TITLE
global > On top and bottom nav, text to have letter-spacing: 1px

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#5]
![image](https://cloud.githubusercontent.com/assets/3534617/15801960/dc861562-2a59-11e6-870c-98a767aea698.png)

![image](https://cloud.githubusercontent.com/assets/3534617/15801959/d7410d50-2a59-11e6-9d91-bf293648c7b9.png)

**Comment by skinall13** [comment]
Top and bottom nav issue solved, we have made font size 18 px with 1 px letter spacing.
Please check the screenshot below:
![header](https://cloud.githubusercontent.com/assets/19643270/15824217/be2a9df4-2c1b-11e6-8370-12c262ef5144.png)
![footer](https://cloud.githubusercontent.com/assets/19643270/15824220/c3d77ea2-2c1b-11e6-90c2-626a9762939b.png)
